=== Jesperkemist/Perovskite_composition/perovskite_composition_schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "$id": "https://raw.githubusercontent.com/Jesperkemist/Perovskite_composition/refs/heads/main/perovskite_composition_schema.json",
    "type": "object",
    "properties": {
        "long_form": {
            "type": "string",
            "description": "The perovskite composition according to IUPAC recommendations, where standard abbreviations are used for all ions. A-ions are listed in alphabetic order, followed by the B-ions in alphabetics order, followed by the X-ions in alphabetic order, all with their stochiometric coefficients. For increased clarity, we recommend enclosing all ions whose abbreviations are 3 letters or longer in parentheses.",
            "examples": ["Cs0.05FA0.78MA0.17PbBr0.5I2.5"]
        },
        "short_form": {
            "type": "string",
            "description": "The long_form stripped of the numeric coefficients. This is a useful key for searching and grouping perovskite data.",
            "examples": ["CsFAMAPbBrI"]
        },
        "composition_estimate": {
            "type": "string",
            "description": "A categorical description of how the composition is estimated. Standard options include: “Estimated from precursor solutions”, “Literature value”, “Estimated from XRD data”, “Estimated from spectroscopic data”, and “Theoretical simulation”.",
            "examples": ["Estimated from precursor solutions", "Literature value", "Estimated from XRD data", "Estimated from spectroscopic data", "Theoretical simulation"]
        },
        "sample_type": {
            "type": "string",
            "description": "A categorical description of the type of sample the data describes. Standard options include: “Polycrystalline film”, “Single crystal”, “Quantum dots”, “Nano rods”, and “Colloidal solution”.",
            "examples": ["Polycrystalline film", "Single crystal", "Quantum dots", "Nano rods", "Colloidal solution"]
        },
        "dimensionality": {
            "type": "string",
            "description": "A categorical description of the dimensionality of the perovskite. Standard options include: “0D”, “1D”, “2D”, “3D”, “2D/3D”. “2D/3D” refers to a situation where a 2D phase is intermixed with a 3D phase but where the overall composition is given by the value in long_form.",
            "examples": ["0D", "1D", "2D", "3D", "2D/3D"]
        },
        "bandgap": {
            "type": "number",
            "minimum": 0,
            "description": "The band gap of the perovskite expressed in electron volt. Details of how the band gap is estimated is suggested to be encapsulated in a separate data schema.",
            "examples": [1.63],
            "unit": "eV"
        },
        "a_ions": {
            "type": "array",
            "description": "A list of dictionaries on the form [{key_1: value_1, key_2: value_2, …}, {key_1: value_1,  …}, …]. Each element in the list represents one A-site ion in the perovskite structure. Each ion is given its own dictionary with the keys listed below.",
            "items": {
                "$ref": "https://raw.githubusercontent.com/Jesperkemist/Perovskite_composition/refs/heads/main/ion_schema.json"
            }
        },
        "b_ions": {
            "type": "array",
            "description": "Same structure as the a_ions",
            "items": {
                "$ref": "https://raw.githubusercontent.com/Jesperkemist/Perovskite_composition/refs/heads/main/ion_schema.json"
            }
        },
        "x_ions": {
            "type": "array",
            "description": "Same structure as the a_ions",
            "items": {
                "$ref": "https://raw.githubusercontent.com/Jesperkemist/Perovskite_composition/refs/heads/main/ion_schema.json"
            }
        },
        "additives_and_impurities": {
            "type": "array",
            "description": "A list of dictionaries on the form: [{key_1: value_1, key_2: value_2, …}, {key_1: value_1,  …}, …]. Each element in the list represents a dictionary with one component that is present in the film but not incorporated into the perovskite crystal structure. Keywords in the dictionaries include: the concentration, the function in the film, i.e. if it is to be considered as a secondary phase, an additive, a dopant or an impurity, and data to uniquely identify the compound including the same key value pairs found in the sections for perovskite ions.",
            "items": {
                "type": "object",
                "properties": {
                    "function": {
                        "type": "string",
                        "description": "The function of the additive or impurity in the film."
                    },
                    "abbreviation": {
                        "type": "string",
                        "description": "The abbreviation used for the additive or impurity."
                    },
                    "concentration": {
                        "type": "number",
                        "description": "The concentration of the additive or impurity."
                    },
                    "concentration_metric": {
                        "type": "string",
                        "description": "The metric used for the concentration of the additive or impurity."
                    },
                    "molecular_formula": {
                        "type": "string",
                        "description": "The Molecular formula which indicates the numbers of each type of atom in a molecule, with no information about the structure."
                    },
                    "smile": {
                        "type": "string",
                        "description": "The canonical SMILE string of the additive or impurity."
                    },
                    "common_name": {
                        "type": "string",
                        "description": "The common or trivial name of the additive or impurity."
                    },
                    "iupac_name": {
                        "type": "string",
                        "description": "The preferred systematic IUPAC name of the additive or impurity."
                    },
                    "cas_number": {
                        "type": "string",
                        "description": "The CAS number for the additive or impurity."
                    }
                },
                "required": [
                    "function",
                    "abbreviation",
                    "concentration",
                    "concentration_metric",
                    "molecular_formula",
                    "smile",
                    "common_name",
                    "iupac_name",
                    "cas_number"
                ]
            }
        }
    },
    "required": [
        "long_form",
        "short_form",
        "composition_estimate",
        "sample_type",
        "dimensionality",
        "bandgap",
        "a_ions",
        "b_ions",
        "x_ions",
        "additives_and_impurities"
    ]
}

=== Jesperkemist/Perovskite_composition/test-2.json
{
    "long_form": "Cs0.05FA0.18MA0.79PbBr0.5I2.5",
    "short_form": "CsFAMAPbBrI",
    "composition_estimate": "Estimated from precursor solutions",
    "sample_type": "Polycrystalline film",
    "dimensionality": "3D",
    "bandgap": 1.63,
    "a_ions": [
        {
            "abbreviation": "Cs",
            "coefficient": "0.05",
            "molecular_formula": "Cs+",
            "smile": "[Cs+]",
            "common_name": "Cesium ion",
            "iupac_name": "Cesium(1+)",
            "cas_number": "18459-37-5",
            "source_compound_smile": "[Cs]",
            "source_compound_iupac_name": "Cesium",
            "source_compound_cas_number": "7440-46-2"
        },
        {
            "abbreviation": "FA",
            "coefficient": "0.18",
            "molecular_formula": "CH5N2+",
            "smile": "C(=[NH2+])N",
            "common_name": "Formamidinium",
            "iupac_name": "aminomethylideneazanium",
            "source_compound_smile": "C(=N)N",
            "source_compound_iupac_name": "methanimidamide",
            "source_compound_cas_number": "463-52-5"
        },
        {
            "abbreviation": "MA",
            "coefficient": "0.79",
            "molecular_formula": "CH6N+",
            "smile": "C[NH3+]",
            "common_name": "Methylammonium",
            "iupac_name": "methylazanium",
            "cas_number": "17000-00-9",
            "source_compound_smile": "CN",
            "source_compound_iupac_name": "methanamine",
            "source_compound_cas_number": "74-89-5"
        }
    ],
    "b_ions": [
        {
            "abbreviation": "Pb",
            "coefficient": "1",
            "molecular_formula": "Pb2+",
            "smile": "[Pb+2]",
            "common_name": "Lead",
            "iupac_name": "lead(2+)",
            "cas_number": "14280-50-3",
            "source_compound_smile": "[Pb]",
            "source_compound_iupac_name": "Lead",
            "source_compound_cas_number": "7439-92-1"
        }
    ],
    "x_ions": [
        {
            "abbreviation": "Br",
            "coefficient": "0.5",
            "molecular_formula": "Br-",
            "smile": "[Br-]",
            "common_name": "Bromide",
            "iupac_name": "Bromide",
            "cas_number": "24959-67-9",
            "source_compound_smile": "BrBr",
            "source_compound_iupac_name": "molecular bromine",
            "source_compound_cas_number": "7726-95-6"
        },
        {
            "abbreviation": "I",
            "coefficient": "2.5",
            "molecular_formula": "I-",
            "smile": "[I-]",
            "common_name": "Iodide",
            "iupac_name": "Iodide",
            "cas_number": "20461-54-5",
            "source_compound_smile": "II",
            "source_compound_iupac_name": "molecular iodine",
            "source_compound_cas_number": "7553-56-2"
        }
    ],
    "additives_and_impurities": [
        {
            "function": "Additive",
            "abbreviation": "RbI",
            "concentration": 0.1,
            "concentration_metric": "wt %",
            "molecular_formula": "RbI",
            "smile": "[Rb+].[I-]",
            "common_name": "Rubidium iodide",
            "iupac_name": "rubidium(1+);iodide",
            "cas_number": "7790-29-6"
        },
        {
            "function": "Impurity",
            "abbreviation": "Fe2+",
            "concentration": 0.001,
            "concentration_metric": "mol %",
            "molecular_formula": "Fe2+",
            "smile": "[Fe+2]",
            "common_name": "Iron(2+)",
            "iupac_name": "iron(2+)",
            "cas_number": "1317-63-1"
        }
    ]
}

=== Jesperkemist/Perovskite_composition/test.json
{
    "long_form": "(PEA)2PbI4",
    "short_form": "(PEA)PbI",
    "composition_estimate": "Estimated from precursor solutions",
    "sample_type": "Polycrystalline film",
    "dimensionality": "2D",
    "bandgap": 2.38,
    "a_ions": [
        {
            "abbreviation": "PEA",
            "coefficient": "2",
            "molecular_formula": "C8H12N+",
            "smile": "C1=CC=C(C=C1)CC[NH3+]",
            "common_name": "Phenylethylammonium",
            "iupac_name": "2-phenylethylazanium",
            "source_compound_smile": "C1=CC=C(C=C1)CCN",
            "source_compound_iupac_name": "2-phenylethanamine",
            "source_compound_cas_number": "64-04-0"
        }
    ],
    "b_ions": [
        {
            "abbreviation": "Pb",
            "coefficient": "1",
            "molecular_formula": "Pb2+",
            "smile": "[Pb+2]",
            "common_name": "Lead",
            "iupac_name": "lead(2+)",
            "cas_number": "14280-50-3",
            "source_compound_smile": "[Pb]",
            "source_compound_iupac_name": "Lead",
            "source_compound_cas_number": "7439-92-1"
        }
    ],
    "x_ions": [
        {
            "abbreviation": "I",
            "coefficient": "4",
            "molecular_formula": "I-",
            "smile": "[I-]",
            "common_name": "Iodide",
            "iupac_name": "Iodide",
            "cas_number": "20461-54-5",
            "source_compound_smile": "II",
            "source_compound_iupac_name": "molecular iodine",
            "source_compound_cas_number": "7553-56-2"
        }
    ],
    "additives_and_impurities": [
        {
            "function": "Additive",
            "abbreviation": "RbI",
            "concentration": 0.1,
            "concentration_metric": "wt %",
            "molecular_formula": "RbI",
            "smile": "[Rb+].[I-]",
            "common_name": "Rubidium iodide",
            "iupac_name": "rubidium(1+);iodide",
            "cas_number": "7790-29-6"
        },
        {
            "function": "Impurity",
            "abbreviation": "Fe2+",
            "concentration": 0.001,
            "concentration_metric": "mol %",
            "molecular_formula": "Fe2+",
            "smile": "[Fe+2]",
            "common_name": "Iron(2+)",
            "iupac_name": "iron(2+)",
            "cas_number": "1317-63-1"
        }
    ]
}
